/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Chat_Friend.java
 *
 * Created on Jun 28, 2010, 12:10:59 AM
 */

package chatapplication;

import java.awt.Color;
import java.awt.Font;
import java.net.*;
import java.io.*;
import java.util.*;
/**
 *
 * @author Ujjwal
 */
public class Chat_Friend extends javax.swing.JFrame {

    boolean isBold=false;
    boolean isItalic=false;
    boolean isUnderline=false;

        Socket s;
	DataInputStream in;
	PrintStream out;

        String ip;

        /** Creates new form Chat_Friend */
    public Chat_Friend(String ip) {

            this.ip=ip;
        initComponents();
        
        getContentPane().setBackground(java.awt.Color.black);
        Font f= jTextArea1.getFont();
        setVisible(true);

    }
    public void connectToServer()
    {
     try
		{
			System.out.println("Trying to connect to Server");
			s= new Socket(ip,5432);
		 	System.out.println("Connection Established with Server");
		 	in=new DataInputStream(s.getInputStream());
		 	out=new PrintStream(s.getOutputStream());
       		 	//chat();
	  	}
	  	catch(Exception e)
	  	{

		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chat_Friend");
        setBackground(java.awt.Color.black);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatapplication/bold_off.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatapplication/italic_off.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatapplication/underline_off.png"))); // NOI18N

        jButton1.setText("Send");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatapplication/bold_on.png")));
        Font f= jTextArea1.getFont();
        if(isBold==true)
        {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatapplication/bold_off.png")));
        jTextArea1.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
         isBold=false;
        }
        else
        {
            
        jTextArea1.setFont(f.deriveFont(f.getStyle()^ Font.BOLD));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatapplication/bold_on.png")));
         isBold=true;
        }



    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       String s= jTextField1.getText();

       Font f= jTextArea1.getFont();
       if(isBold==true)
       {
           //jTextArea1.setFont(f.deriveFont(f.getStyle() ^ Font.BOLD));
       }
       else
       {
          // jTextArea1.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
       }
       jTextArea1.append("ME:");
       //jTextArea1.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
       jTextArea1.append(s);
       jTextArea1.append("\n");
       System.out.println("putting in the socket");
       out.println(s);
       jTextField1.setText("");


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


public void incomingChat(String str)
{
     jTextArea1.append("HIM:");
       //jTextArea1.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
       jTextArea1.append(str);
       jTextArea1.append("\n");
    
}

}
